### ISSUE TITLE
Add 24fps / 25fps to 1296p / 1440p resolution

### ISSUE THREAD

**Issue by ianmustafa** [alex-agency/XYC#10]
I don't know if it's possible, but it'd be cool if we can shoot 24fps in native rather than convert 30fps to 24fps or 25fps.

**Comment by justinbacle** [comment]
You can already shoot in 24fps when using 1080p and higher resolutions.

**Comment by alex-agency** [comment]
Sure, I'll add it as soon as check how it works.
I mean 24fps for 1280x720, 1280x960, 1600x1200, 1920x1080 and 25fps for 2304x1296, 2560x1440. 

And I'm going to fix 2560x1440 resolution, which is currently not working. 
It'll be scaled resolution from 2304x1296. 
You can read about it in the following posts: https://dashcamtalk.com/forum/threads/yi-hacked-resolution-2304x1296-30fps-35mbits.11589/page-34

**Comment by alex-agency** [comment]
Added 24 fps for 1280x720, 1280x960, 1600x1200, 1920x1080 resolutions.
Fixed issue with 2560x1440 resolution.
It's not possible to set 25fps for 2304x1296, 2560x1440 resolutions. It looks this one can't support by 1.2.13 firmware.
