### ISSUE TITLE
RAW on timelapse

### ISSUE THREAD

**Issue by atlaware** [alex-agency/XYC#19]
Hi,
I don't think that this problem is exactly xyc script fault, but at least related:
the RAW files created with timelapse function (10s) with yi official app or with xyc script do RAW files (13mb) that doesn't work, but if I do normal shoot with camera botton RAW files is bigger (31mb) and work correctly with raw2dng converter, only for me?

Thank you.

**Comment by alex-agency** [comment]
Hi, 
You're right it's works exactly as you described. It is common problem. If you want using RAW with timelapse function then try timelapse option in the xyc script where you can use bigger duration range, RAW and other features.

Best Regards,
Alex
