### ISSUE TITLE
Firmware 1.2.12

### ISSUE THREAD

**Issue by PJanisio** [alex-agency/XYC#3]
/tmp/fuse_d # ./xyc.sh
: not foundine 45:
: not foundine 55:
: not foundine 66:
: not foundine 153:
./xyc.sh: line 196: syntax error: unexpected word (expecting "in")

**Comment by alex-agency** [comment]
Its happen because you have Windows line ending. You need Unix line ending for run script in Linux.
Try to change line ending via Notepad++ or Sublime Text editors.
If you download file without changes you won't have any line ending issues.

**Comment by PJanisio** [comment]
You were right. But i wasnt editing the .sh file. I have downloded your scrip by cloning repo from github by and opened by github repo app, so possibly this app modified line ending (wired).

Great job btw!
