### ISSUE TITLE
[F.REQ] Use this externally under Linux

### ISSUE THREAD

**Issue by ricardobalk** [alex-agency/XYC#8]
Hey, I used this script to configure the Xiaomi Yi from Linux (externally) and download it from the website. How?

1 Cloned this repository

```
git clone https://github.com/alex-agency/XYC.git
cd XYC
```

2 Made fuse_d directory and autoexec.ash

```
mkdir /tmp/fuse_d
touch /tmp/fuse_d/autoexec.ash
```

3 Executed the script

```
bash xyc.sh
```

4 Copied the resulting Xiaomi script to the webserver

```
cp /tmp/fuse_d/autoexec.ash /var/www/autoexec.ash
```

This works but it would be awesome if you integrate this into the script (:

**Comment by alex-agency** [comment]
Done. 

I've added XYC Update option which automates your 1-3 steps. 

Now XYC checks /tmp/fuse_d directory if it doesn't exist will be used current script directory. 
Also in case of /tmp/fuse_d dir doesn't exist, but /var/www dir is present then XYC will use /var/www for generating autoexec.ash. This one it is step 4. Don't forget to remove /tmp/fuse_d dir from your system.

Regards,
Alex
