### ISSUE TITLE
Frame Rates

### ISSUE THREAD

**Issue by bakersdozen** [alex-agency/XYC#9]
Hi Alex, thanks for your work.
Any chance of adding the other frame rates?
ie 48fps

**Comment by alex-agency** [comment]
Sure. I'll add it, today or tomorrow.

**Comment by bakersdozen** [comment]
Great! Thank you so much..for this and your work so far. It takes the Yi so much further and amazing to incorporate Nutseys work too. Much appreciated.

**Comment by alex-agency** [comment]
You're welcome. )
I've added 48 fps and improved script performance.
